### ISSUE TITLE
Notification not received when app is closed in Background

### ISSUE THREAD

**Issue by hemnath11** [sebaferreras/Ionic2-FirebaseDemo#1] opened 2017-06-10 08:22 UTC
After App is removed background running (killed)... notification not received But response status  get success...

{
  "multicast_id": 4863810968744040251,
  "success": 1,
  "failure": 0,
  "canonical_ids": 0,
  "results": [
    {
      "message_id": "0:1497082664415269%b8351284b8351284"
    }
  ]
}

**Comment by sebaferreras** [comment] 2017-06-10 10:40
Is that happening on ios or android? The demo shows the notifications properly, even when the app is not being executed, so there must be something else in your end. 

Besides, the plugin itself shows the notification in the notification bar, so if that part is not working, check all the required steps to setup the plugin.

**Comment by hemnath11** [comment] 2017-06-10 11:27
happening in Android

**Comment by sebaferreras** [comment] 2017-06-10 12:19
Please take a look in your implementation, since it must be an error on your end. Just checked this demo and works properly for both android and ios, when the app is closed. 

I'm closing this issue because I can not reproduce the issue on my end.

**Closed by sebaferreras** 2017-06-10 12:19 UTC

**Comment by hemnath11** [comment] 2017-06-13 12:10
It will working when app is closed but normally we closed app means it will running in the background.. what i'm asking is when we end(killed) the app in background that time notifications are not receiving... Again we start the app means notifications received....

**Comment by sebaferreras** [comment] 2017-06-13 12:28
> Just checked this demo and works properly for both android and ios, when the app is closed.

Like I said, I've tested the demo with the application **not being executed in the background** and everything works properly.  

I've attached a zip file with a video, showing the demo working properly when the app is no being executed: [firebaseDemo.mp4.zip](https://github.com/sebaferreras/Ionic2-FirebaseDemo/files/1071334/firebaseDemo.mp4.zip)

Take a look at the steps required to set up the firebase account, and the [steps required by the plugin](https://github.com/arnesson/cordova-plugin-firebase#installation) to see if you missed something, since the issue only happens on your end.

**Comment by hemnath11** [comment] 2017-06-20 05:36
Thank you for your information... i'm trying this firebaseDemo step by step your instruction.

I've attached my tested video. PLz Help me how to fix this.

[test_push.mp4.zip](https://github.com/hemnath11/Ionic2-FirebaseDemo/blob/master/test_push.zip)
